### ISSUE TITLE
Attribution to the original

### ISSUE THREAD

**Issue by ericmjl** [leriomaggio/network-analysis-mscx18#1]
Hello @leriomaggio,

One of my collaborators on [Network Analysis Made Simple](https://github.com/ericmjl/Network-Analysis-Made-Simple), @MridulS, brought to my attention your repository. Looking through the notebooks, it appears that the material is copied over from our original and is lightly modified to suit the purposes of the summer school that you will be leading.

Imitation is the best form of flattery, and I'm glad that you find the material useful and would like to present it to an audience that neither Mridul nor myself would have the time or opportunity to reach! I would also find it to be a great pity if someone else discovered that you were not the original creator of the material, which the front page of the repository seems to imply, and leveled an accusation of plagiarism (which is not the intent of my post here, I hope that becomes clear to you by the end of this post). 

While there is a single-line attribution inside Notebook 1, I think it is insufficient to prevent misunderstandings by other people, and I would like to help you make sure that this doesn't happen. 

If you would like to provide proper attribution and protect yourself against potential accusations, I have a suggestion on wording that you can include at the bottom of the README, to make it clear that this is material modified from another original repository:

> This material is a fork of the original Network Analysis Made Simple material created by Eric Ma and Mridul Seth. The original material can be found at: https://github.com/ericmjl/Network-Analysis-Made-Simple/. 

Additionally, in an international setting, the "author" is most often understood as the "original creator" of the material. I am most inclined to believe that there were some misunderstandings with language at play here. I would suggest changing "Author: Valerio Maggio" to "Workshop Leader: Valerio Maggio", again, to help prevent misunderstandings from showing up. 

On a separate note, all the best for your summer workshop in Italy! If there are recordings, I would like to link to them in the original repository, so that others may see it.

Cheers,
Eric

**Comment by ericmjl** [comment]
Hello @leriomaggio, just wanted to check in again regarding this issue. I'd like to handle this constructively without escalating it anywhere, so please let me know what your thoughts are.

**Comment by leriomaggio** [comment]
Hello @ericmjl 
I am very sorry for all this fuss and mess about this repository and materials.

Please let me go through the points - random order, so equally important:

*) Please accept my apologies if I respond you lately - I did not receive any notification about this ISSUE nor GitHub drew me this to my attention. really sorry

*) I did not mean to got the attribution of all your material nor claiming that I am the **original** author of the content of this tutorial.
In fact, I clearly reported the original ownership since the very beginning in the WarmUp Notebook, credits section: https://github.com/leriomaggio/network-analysis-mscx18/blob/master/1-warmup.ipynb
as I am glad you noticed.
TBH I originally forked your repository - but for some reasons I finally decided to work on this new repo having in mind to include all the changes I made in my "version" of the notebooks in my fork and open a PR for you to review :) - unfortunately I had not really the time to do so, though.

Indeed, the modifications I made to the materials were not intended to suit the needs of the school but to update and (slightly) improve (IMHO) the already excellent content.

Plus: I think I already met @MridulS once in a EuroSciPy Conference - he explicitly caught up with me via email and he kindly offered his help to prepare the material. After that, nothing unfortunately and all of a sudden *this* finally came out. A bit sorry about this, indeed.
He could have written an email to draw this to my attention or sent me a tweet - all my contacts are there.
Anyway, this was just to say that I did not mean to ignore you - I simply did not notice! :)

That said, please let me just summarise and make crystal clear that:

- I did really liked all the material in your tutorial and I thank you for that and for sharing;
- I do apologise for missing to report the credits I reported in the warmup notebook in also in the README file;
- I am definitely going to include the changes you suggested in the README file.
_I agree with you that the README file is a kind of _manifesto_ of the repo. Simply forgot to replicate the credits attribution that I already reported in the notebook._

Plus: please let me add that - as you might have noticed from my GitHub profile - I already did other tutorials in many conferences around Europe (the one on DL w/ Keras and TF got quite an attention) and so I hope you believe me if I say that claiming the attribution of somebody's work is completely out of the question for me :)

**Comment by leriomaggio** [comment]
Done @ericmjl @MridulS. 
Plus Updated the License to MIT.
Please let me know if everything is fine now for you so I can close this issue :)

Hope for the best and cheers,
Valerio

**Comment by ericmjl** [comment]
Hi @leriomaggio,

Thank you for getting back! Sorry if the DCMA takedown notice gave you a fright; I figured this would be the only way to get your attention, since after two weeks of waiting, I didn't want to handle this on an even more public forum (like Twitter). I was assuming best intentions (hopefully my messaging above didn't communicate otherwise), and also wanted to resolve this issue sooner rather than later.

I'm happy with the changes made to the README, and I will hopefully be able to speak for @MridulS as well that he will be happy with the changes too. 

Btw, are there recordings of your workshop? I'd like to link them in the original repository too. Also, if you have improvements, I'd love to hear them!

Cheers,
Eric

**Comment by leriomaggio** [comment]
Hi @ericmjl.
No worries for the DCMA. I initially got worried at first sight, but then I read your message and completely understood your intentions - and I thank you again for that!
Happy that you saw my good intentions, too.

Unfortunately the school had no recordings: it was a very "difficult" setting - from the perspective of the internet connection - Internet was definitely not a thing there as it was a small island in the middle of the Mediterranean Sea :) 

That said, it was very experimental for the organisers to include a tutorial workshop in their school. 
I think they finally liked the idea and hopefully will repeat the experience next year.
I will definitely let you know more about this in the future. 

As for the repository, then. This is how I intend to proceed further. 
I realise that the original fork I did to your repo was set private to avoid confusions but nothing has been changed there in terms of notebooks and content.
I mainly kept on working on this one.

So, I am going to align my fork with this repository - with all credits and attribution reference to the original material - and for the changes that I think may be of any interest for you to review, I am going to submit a PR so that I can also contribute to the repo. 

How does this sound to you?

Cheers,
Valerio
